### PR TITLE
Enable interception when the values for an S3 repository are updated

### PR DESCRIPTION
**Pull request by rwitzel**
Make `S3ConfigurationRepository` extendable

### CODE REVIEW

**Comment by lmineiro** [comment]
Are you planning on contributing the callback mechanism for this or you just plan on extending this repository for you personally?

**Comment by amjedonline** [comment]
If this is to add callback, I suggest you create an AutoSynchronous Repository type. Please check  [GitCacheLoader](https://github.com/rwitzel/baigan-config/blob/2648f46e42fd76cf3db66a22df9e053f632ec7f8/src/main/java/org/zalando/baigan/service/github/GitCacheLoader.java) and [GitConfigurationRepository](https://github.com/rwitzel/baigan-config/blob/2648f46e42fd76cf3db66a22df9e053f632ec7f8/src/main/java/org/zalando/baigan/service/github/GitConfigurationRepository.java). Refactoring to implement this in some uniform way.

**Comment by rwitzel** [comment]
@lmineiro We want to extend the repository for own purposes.

**Comment by lmineiro** [comment]
👍

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Comment by lukasniemeier-zalando** [comment]
@rwitzel I have released `0.14.1` with this change. It will appear soonish in Nexus.

**Pull request merged**
